// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEUKfJARpJZIvzdqTJarmRp9S0fbcBIJo',
    appId: '1:170288600357:web:922668fe3c598b063ff6cc',
    messagingSenderId: '170288600357',
    projectId: 'nozofibi',
    authDomain: 'nozofibi.firebaseapp.com',
    storageBucket: 'nozofibi.firebasestorage.app',
    measurementId: 'G-6W0M64W300',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvGufikdNErmjD9a-F-JhwCOwSO6Ggn2k',
    appId: '1:170288600357:android:ba2b7b82b635847f3ff6cc',
    messagingSenderId: '170288600357',
    projectId: 'nozofibi',
    storageBucket: 'nozofibi.firebasestorage.app',
  );

}